version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - secret:/data/file
    ports:
      - "8000:8097"
    command: [ "server", "--port", "8097", "--path", "/data/file/file.json" ]
    healthcheck:
      test: [ "CMD", "server", "ping", "--port", "8097" ]
      interval: 30s
      retries: 3
      timeout: 15s
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/var/lib/redis
    #    ports:
    #      - "8000:6379"
#    command: [ "server", "--redis-url", "localhost:6379" ]
volumes:
  secret:
  redis-data:


